version: '3.3'

services:
    my-nginx:
        image: nginx:1.12.0
        ports:
            - "80:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/firstrun-sites-default.conf:/etc/nginx/conf.d/default.conf
            - ${WEB_ROOT}:/var/www
        links:
           - my-php
    my-php: 
        build: ./php
        image: kchgoh/php
        volumes:
            - ${WEB_ROOT}:/var/www
    my-mysql:
        image: mariadb:10.1
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
            - ./mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
            - ${DB_ROOT}:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

